// Vuejs-p5/generator/src/components/Navbar.vue
<template>
  <navbar>
    <div class="navbar navbar--vue">
        <div class="container container__mobile">
          <div class="navbar__inner flex">
            <h1 class="vue-color"> {{ title }}</h1>
            <nav>
                <ul>
                    <li class="navbar__link--vanilla"><a href="http://ocr-p5-vanillajs.folio-jmg.fr/">VanillaJS</a></li>
                    <li class="navbar__link--react"><a href="http://ocr-p5-react.folio-jmg.fr/">React</a></li>
                </ul>
            </nav>
          </div>
        </div>
    </div>
  </navbar>
</template>

<script>
export default {
name: "navbar.vue",
  data () {
  return {
    title: 'Générateur de citations'
  }
  }
}
</script>

<style scoped>

</style>

// React-p5/src/components/Navbar/Navbar.js
import React from "react";

const Navbar = () => {
    return (
        <div>
            <navbar>
                <div className="navbar navbar__background--react">
                    <div className="container">
                    <div className="navbar__inner flex">
                        <h1 className="react-color"> Générateur de Citations React</h1>
                        <nav>
                            <ul>
                                <li className="navbar__link--vanilla"><a href="http://ocr-p5-vanillajs.folio-jmg.fr/">VanillaJS</a></li>
                                <li className="navbar__link--vuejs"><a href="http://ocr-p5-vuejs.folio-jmg.fr/">Vuejs</a></li>
                            </ul>
                        </nav>
                    </div>
                    </div>
                </div>
  </navbar>
            
        </div>
    )
}

export default Navbar
